version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /Users/ivan.kalashnikov/Documents/Programming/personal/ansible-nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud-admin
  app:
    image: nextcloud:stable
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /Users/ivan.kalashnikov/Documents/Programming/personal/ansible-nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud-admin
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_PASSWORD=
      - NEXTCLOUD_ADMIN_USER=
      - NEXTCLOUD_TRUSTED_DOMAINS=
      - OVERWRITEPROTOCOL=https
      - CLIENT_MAX_BODY_SIZE=400G
      - UPLOAD_MAX_FILESIZE=400G


